name: Deploy Laravel App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Pull latest code
        run: |
          cd /var/www/laravel
          git pull origin main

      - name: Install PHP dependencies
        run: |
          cd /var/www/laravel
          composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Run database migrations
        run: |
          cd /var/www/laravel
          php artisan migrate --force

      - name: Optimize Laravel config
        run: |
          cd /var/www/laravel
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache
